# Generated by Django 5.1.6 on 2025-10-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_puzzle',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
